---
title: Test BiocNeighbors for UCell score smoothing
author: 
- Massimo Andreatta^[massimo.andreatta@unil.ch]
- Santiago Carmona^[santiago.carmona@unil.ch]
date: "03/08/2022"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'SmoothNN.html'))})
#output: html_notebook
---


```{r message=F, warning=F}
#renv::restore()

#BiocManager::install("UCell")
#remotes::install_github("carmonalab/UCell", ref="dev")  #development version

library(UCell)
```

#Object at: https://drive.switch.ch/index.php/s/3kM5PQ0tQaG6d6A
```{r}
library(ggplot2)
library(Seurat)
library(SeuratDisk)

reduction = "wnn.umap"
#reduction = "umap"

pbmc <- readRDS("data/pbmc_multimodal.downsampled20k.Tcell.seurat.RNA.rds")
#pbmc <- LoadH5Seurat("../Azimuth/data/pbmc_multimodal.h5seurat")

DimPlot(object = pbmc, reduction = "wnn.umap", group.by = "celltype.l2", label = TRUE, label.size = 3, repel = TRUE)
DimPlot(object = pbmc, reduction = "umap", group.by = "celltype.l2", label = TRUE, label.size = 3, repel = TRUE)
```

#Get some gene sets
```{r}
signatures <- list()
signatures$CD4T <- c("CD4","CD40LG")
signatures$CD8T <- c("CD8A","CD8B")
signatures$Treg <- c("FOXP3","IL2RA")
signatures$MAIT <- c("KLRB1", "SLC4A10", "NCR3")
signatures$Tcell_gd <- c("TRDC", "TRGC1", "TRGC2", "TRDV1","TRAC-","TRBC1-","TRBC2-")
signatures$NK <- c("FGFBP2", "SPON2", "KLRF1", "FCGR3A", "KLRD1", "TRDC","CD3E-","CD3G-")

t1 <- Sys.time()
pbmc <- AddModuleScore_UCell(pbmc, features = signatures, name = NULL, ncores=8)
t2 <- Sys.time()
t2 - t1

FeaturePlot(pbmc, reduction = reduction,
            features = c("CD4T","CD8T","Tcell_gd","MAIT"), max.cutoff = 'q99')

```

Find NN
```{r}
library(BiocNeighbors)
k <- 10

space <- pbmc@reductions$pca@cell.embeddings
#space <- pbmc@reductions$wnn.umap@cell.embeddings

nn <- findKNN(space, k=k, BNPARAM=AnnoyParam())
```

Time benchmark
```{r eval=F}
library(BiocNeighbors)
k <- 50

space <- pbmc@reductions$pca@cell.embeddings

t1 <- Sys.time()
#Method1
nn <- findKNN(space, k=k, BNPARAM=AnnoyParam())
t2 <- Sys.time()
t2 - t1


#Method2
t1 <- Sys.time()
nn <- findKNN(space, k=k, BNPARAM=HnswParam())
t2 <- Sys.time()
t2 - t1

#Multi-core?
t1 <- Sys.time()
BPPARAM <- BiocParallel::MulticoreParam(workers = 8)
#Method1
nn <- findKNN(space, k=k, BNPARAM=AnnoyParam(), BPPARAM=BPPARAM)
t2 <- Sys.time()
t2 - t1
```

Did it work?
```{r}
DimPlot(pbmc, reduction = reduction, cells.highlight = nn$index[1,], sizes.highlight = 2, raster=F) +
  NoLegend() + theme(aspect.ratio=1)
DimPlot(pbmc, reduction = reduction, cells.highlight = nn$index[2,], sizes.highlight = 2, raster=F) +
  NoLegend() + theme(aspect.ratio=1)

maxrow <- which(nn$distance == max(nn$distance), arr.ind = TRUE)[1]
nn$distance[maxrow,]

DimPlot(pbmc, reduction = reduction, cells.highlight = nn$index[maxrow,], sizes.highlight = 2, raster=F) +
  NoLegend() + theme(aspect.ratio=1)
```


Smooth UCell scores by averaging neighbors
```{r}
sig.cols <- names(signatures)
data <- pbmc

w.df <- vapply(sig.cols, FUN.VALUE = numeric(ncol(data)), FUN=function(s) {
  
  score.sig <- data@meta.data[,s]
  weighted.scores <- vapply(X = 1:nrow(nn$index),
                            FUN.VALUE = numeric(1),
                            FUN = function(x) {
                              r <- nn$index[x,]
                              r <- c(x,r)
                              
                              d <- nn$distance[x,]
                              d <- c(d[1],d)
                              
                              w <- 1/(0.01+d)
                              
                              sum(w * score.sig[r])/sum(w)
                            })
})
rownames(w.df) <- colnames(data)
colnames(w.df) <- paste0(colnames(w.df),"_NN")
head(w.df)
```

Add to metadata
```{r fig.height=3}
pbmc <- AddMetaData(pbmc, metadata = as.data.frame(w.df))
```

```{r fig.height=3}
FeaturePlot(pbmc, reduction = reduction,
            features = c("CD4T","CD4T_NN","CD8T","CD8T_NN"))

FeaturePlot(pbmc, reduction = reduction,
            features = c("Tcell_gd","Tcell_gd_NN","MAIT","MAIT_NN"))

FeaturePlot(pbmc, reduction = reduction,
            features = c("Treg","Treg_NN","NK","NK_NN"))
```
Using the new function implemented in UCell>=2.1.2
```{r fig.height=2.5, fig.width=4}
pbmc <- SmoothKNN(pbmc, signature.names = names(signatures), reduction="pca")

FeaturePlot(pbmc, reduction = reduction,
            features = c("Treg","Treg_kNN","NK","NK_kNN"))

pbmc <- SmoothKNN(pbmc, signature.names = names(signatures), reduction="wnn.umap", suffix = "_UM")

FeaturePlot(pbmc, reduction = reduction,
            features = c("Treg","Treg_UM","NK","NK_UM"))

```
Can we use it to smooth gene expression?
```{r fig.height=2.5, fig.width=4}
genes <- c("CD4","CD8A")
expr <- as.matrix(pbmc@assays$SCT@data[genes,])

pbmc <- AddMetaData(pbmc, metadata=as.data.frame(t(expr)))

pbmc <- SmoothKNN(pbmc, signature.names = genes, reduction="pca", k=100)

FeaturePlot(pbmc, reduction = reduction,
            features = c("CD4","CD4_kNN","CD8A","CD8A_kNN"))

```

With SingleCellExperiment
```{r}
library(SingleCellExperiment)
sce <- as.SingleCellExperiment(pbmc)

sce <- SmoothKNN(sce, signature.names = c("CD4","CD8A","TCF7"),
                 suffix = "smoothed", reduction = 'PCA', sce.expname = 'RNA')

```

Parallel processing
```{r}
library(BiocParallel)
t1 <- Sys.time()
pbmc <- SmoothKNN(pbmc, signature.names = names(signatures), reduction="pca")
t2 <- Sys.time()
t2 - t1

t1 <- Sys.time()
pbmc <- SmoothKNN(pbmc, signature.names = names(signatures), reduction="pca", BPPARAM = MulticoreParam(workers = 4))
t2 <- Sys.time()
t2 - t1
```

#Break cases:
1) k > number of cells
```{r}
cells <- colnames(pbmc)[1:5]
sub <- subset(pbmc, cells=cells)

sub <- SmoothKNN(sub, signature.names = names(signatures), reduction="pca")
```

2) number of cells==1
```{r}
cells <- colnames(pbmc)[1]
sub2 <- subset(pbmc, cells=cells)

sub2 <- SmoothKNN(sub2, signature.names = names(signatures), reduction="pca")
```

3) UCell scoring with 1 cell in object
```{r}
cells <- colnames(pbmc)[1]
sub2 <- subset(pbmc, cells=cells)

sub2 <- AddModuleScore_UCell(sub2, features = signatures)
```





